# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Words' do
  pod 'BubbleTransition', '~> 2.0.0'

  use_frameworks!

  # Pods for Words

  target 'WordsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WordsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
